edition = "2021"
binop_separator = "Back"
brace_style = "PreferSameLine"
tab_spaces = 4
wrap_comments = true

fn_single_line = true
where_single_line = true
format_strings = true
imports_granularity = "Module"
reorder_impl_items = true
group_imports = "StdExternalCrate"
